# Generated by Django 5.0.4 on 2024-05-02 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_tag_user_utilizador_user_alter_review_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 5, 2, 13, 5, 28, 509251, tzinfo=datetime.timezone.utc)),
        ),
    ]
