# Generated by Django 5.0.4 on 2024-05-03 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_place_rating_alter_review_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 23, 24, 15, 877354, tzinfo=datetime.timezone.utc)),
        ),
    ]
