# Generated by Django 5.0.4 on 2024-05-07 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_review_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
