# Generated by Django 5.0.4 on 2024-05-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_review_data_alter_utilizador_profileimage'),
        ('myapi', '0007_alter_review_data'),
    ]

    operations = [
    ]
