# Generated by Django 5.0.4 on 2024-05-11 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_merge_20240508_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='mainImage',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewID',
        ),
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='profileImage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
